import numpy as np
import torch 


"""
LOAD TORCH MODEL BASED ON YAML CONF FILE (WHICH MODEL, WHICH FEATURES)

LOAD SIGNALS FROM ONE TAKE AND PERFORM INFERENCE FOR EACH SIGNAL (IF NEEDED DO AVERAGING)

COMPUTE RESULTS (CF MATRIX)

PERFORM SEQ DECISION MAKING ON THE INFERENCE 


"""