/**
 * Arduino Nano 33 BLE Sense — STREAMING log-mel + CNN2D + EWMA leak monitor
 * =========================================================================
 *
 * One integrated sketch:  record (PDM) -> log-mel patches -> average -> CNN2D
 * inference -> EWMA smoothing -> LED / Serial decision.  Runs continuously.
 *
 * Built from three verified sketches:
 *   - vent_leak_full_mfcc_arduino_nano_33.ino  (ring buffer, PDM ISR, EWMA)
 *   - extract_logmel_nano33.ino                (mel tables, FFT, dB, patches)
 *   - test_cnn_2d.ino                          (TFLite Micro CNN2D inference)
 * The feature-extraction and inference math are copied verbatim from those
 * (already numerically validated against librosa 0.11.0), so this file only
 * adds the streaming glue and the 8-patch averaging.
 *
 *
 * THE FEATURE THIS MODEL EATS
 * ---------------------------
 * The CNN2D input is ONE (N_MELS x PATCH_FRAMES) log-mel patch that is the
 * AVERAGE of N_PATCHES patches cut with hop PATCH_HOP from the decision
 * window's dB spectrogram:
 *
 *     window spectrogram (N_MELS x FRAMES_PER_DECISION, mel-power)
 *        -> power_to_db(ref = global max over the window, top_db=80)
 *        -> cut N_PATCHES patches of PATCH_FRAMES frames, hop PATCH_HOP
 *        -> mean over the N_PATCHES patches  ->  (N_MELS x PATCH_FRAMES)
 *        -> CNN2D
 *
 *     FRAMES_PER_DECISION = PATCH_FRAMES + (N_PATCHES-1)*PATCH_HOP
 *                         = 24 + 7*4 = 52 frames  (~1.63 s @ 16 kHz)
 *
 *
 * WHY WE DON'T STORE THE RAW CLIP
 * -------------------------------
 * ref=np.max is GLOBAL over the window, so the dB values (and hence the patch
 * mean) can't be finalized until every frame in the window is seen. But the
 * only thing that has to survive until then is the mel-POWER spectrogram of the
 * window: N_MELS * FRAMES_PER_DECISION = 40*52 = 2080 floats ~= 8.3 KB. We fill
 * that column-by-column as audio streams in (no big audio buffer), and when the
 * window is full we do global-max -> dB -> patch-average -> inference. This is
 * the memory-cheap, parity-correct version of a "running mean over patches".
 *
 *
 * TWO FEATURE MODES (compile-time)
 * --------------------------------
 *   USE_CLIP_BUFFER 0  (MODE A, default, recommended):
 *       Streaming. Frames are computed continuously from the ring buffer with
 *       NO center=True zero-padding. Window interior matches training exactly;
 *       only the ~512-sample window edges differ (real audio instead of zeros).
 *       Tiny RAM: no raw-clip buffer.
 *
 *   USE_CLIP_BUFFER 1  (MODE B, for on-device cross-validation):
 *       Buffers CLIP_LEN int16 samples, then runs the exact center=True
 *       framing from your verified extract_logmel_nano33.ino. Bit-for-bit the
 *       same as training's per-clip pipeline, at the cost of a ~52 KB buffer.
 *       Use this to confirm MODE A is close enough on your hardware.
 *
 *
 * PARITY THINGS THAT BITE (verify against YOUR training config)
 * -------------------------------------------------------------
 *  1. PDM int16 is divided by 32768.0f before the extractor. With ref=max the
 *     dB spectrogram is gain-invariant EXCEPT for the AMIN (1e-10) floor, which
 *     only lands correctly if the amplitude scale matches training (~[-1,1]).
 *  2. The global-max ref window == the 8-patch decision window (52 frames).
 *     If training computed ref=max over a DIFFERENT clip length, set CLIP_LEN /
 *     N_PATCHES / PATCH_HOP so FRAMES_PER_DECISION equals that clip's frames.
 *  3. Periodic Hann (0.5*(1-cos(2*pi*n/N))), Slaney mel + Slaney area norm.
 *  4. CNN2D input is mel-major: index = mel*PATCH_FRAMES + frame  (NHWC H=mel).
 *  5. Export the .tflite WITHOUT trailing softmax (raw logits); softmax here.
 *
 * Needs: model.h defining `g_model` (your CNN2D, same one test_cnn_2d.ino used).
 */

#include <PDM.h>
#include <math.h>
#include <string.h>
#include <Chirale_TensorFlowLite.h>
#include "model.h"
//#include "scaler.h"   // generated by the INT8 conversion notebook
#include "saved_features.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/schema/schema_generated.h"

/* ========================= Configuration ========================= */
// ---- audio / STFT (must match librosa training params) ----
#define SAMPLE_RATE    16000
#define N_FFT          1024
#define HOP_LENGTH     512
#define N_MELS         40
#define MEL_FMIN       0.0f
#define MEL_FMAX       (SAMPLE_RATE / 2.0f)   // fmax=None -> Nyquist (8000)
#define AMIN           1e-10f                 // power_to_db amin
#define TOP_DB         80.0f                  // power_to_db top_db

// ---- patch / averaging (the "8 patches, hop 4" feature) ----
#define PATCH_FRAMES   24                     // frames per patch  (CNN width W)
#define PATCH_HOP      4                      // hop between patches, in frames
#define N_PATCHES      8                      // patches averaged into 1 input

// ---- feature mode: 0 = streaming (cheap), 1 = clip buffer (exact center=True) ----
#define USE_CLIP_BUFFER 0

// ---- CNN2D geometry (matches test_cnn_2d.ino) ----
#define N_CLASSES      2
#define LEAK_INDEX     1                      // output index treated as "leak"

// ---- EWMA sequential decision layer ----
#define EWMA_ALPHA     0.20f                  // smoothing factor (0..1)
#define EWMA_THRESHOLD 0.50f                  // decision threshold on smoothed p
#define EWMA_RESET_PER_WINDOW 0               // 1 = restart EWMA each window,
                                              // 0 = smooth across windows (deploy)

// ---- misc ----
#define DEBUG_PRINT    1                      // 1 = verbose Serial (means, timing)

/* ---- derived: number of spectrogram frames per decision window ---- */
#define FRAMES_PER_DECISION  (PATCH_FRAMES + (N_PATCHES - 1) * PATCH_HOP)   // 52
// Equivalent raw-sample span (streaming, no center pad):
//   ~ (FRAMES_PER_DECISION-1)*HOP_LENGTH + N_FFT  ~= 27136 samples (~1.70 s)
// This is the "how many samples before feature extraction" knob, expressed in
// frames. To change it, change N_PATCHES / PATCH_HOP / PATCH_FRAMES above.

/* ---- MODE B only: raw clip length. Pick so 1 + CLIP_LEN/HOP == frames ---- */
#if USE_CLIP_BUFFER
  #define CLIP_LEN     ((FRAMES_PER_DECISION - 1) * HOP_LENGTH)   // 51*512 = 26112
  #define MAX_FRAMES   (1 + CLIP_LEN / HOP_LENGTH)                // -> 52
#endif

static const int K = N_FFT / 2 + 1;           // 513 rfft bins
#define MEL_W_MAX      1200                    // sparse mel weights (~981 nonzero)
#define PATCH_LEN      (N_MELS * PATCH_FRAMES) // CNN input length = 960

/* ========================= Buffers ========================= */
// Ring buffer for the PDM ISR (power of two -> index masking).
#define RING_SIZE      8192 //4096
static const int RING_MASK = RING_SIZE - 1;
static volatile int16_t  audioRing[RING_SIZE];
static volatile uint32_t ringWrite = 0;       // ISR-owned
static uint32_t          ringRead  = 0;       // loop-owned

// Precomputed tables (built once).
static float hannP[N_FFT];                     // periodic Hann
static float twCos[N_FFT / 2];                 //  cos(2*pi*k/N)
static float twSin[N_FFT / 2];                 // -sin(2*pi*k/N)
static float melWeights[MEL_W_MAX];            // concatenated triangular weights
static int   melStart[N_MELS];                 // first FFT bin of each filter
static int   melLen[N_MELS];                   // bins in each filter
static int   melOff[N_MELS];                   // offset into melWeights[]
static int   melTotal = 0;

// FFT / frame working buffers.
static float frameBuf[N_FFT];                  // current overlapping frame (float)
static float fftRe[N_FFT];
static float fftIm[N_FFT];
static float powr[K];                          // one frame's power spectrum

// Decision-window mel-POWER spectrogram, mel-major: specWin[m*FRAMES + t].
static float specWin[N_MELS * FRAMES_PER_DECISION];
static int   specCol = 0;                      // columns filled so far

// Averaged patch fed to the CNN (mel-major: meanPatch[m*PATCH_FRAMES + f]).
static float meanPatch[PATCH_LEN];

#if USE_CLIP_BUFFER
  static int16_t clipBuf[CLIP_LEN];            // raw audio (MODE B only)
  static int     clipFill = 0;
#endif

// Frame priming (need N_FFT/HOP hops before the first full frame).
static int hopsLoaded = 0;

// EWMA state.
static float ewma = 0.0f;
static bool  ewmaInit = false;

// Timing.
static unsigned long tFeat0, tInf0;
static uint64_t totalFrameComputeUs = 0;

/* ========================= TFLite Micro ========================= */
namespace {
  const tflite::Model*      model       = nullptr;
  tflite::MicroInterpreter* interpreter = nullptr;
  TfLiteTensor*             input       = nullptr;
  TfLiteTensor*             output      = nullptr;
  tflite::MicroMutableOpResolver<8> resolver;   // ops registered in setup()

  // conv1 output 40*24*16 = 15360 floats -> ~64 KB peak (float32 model).
  // Drop to ~24*1024 for an int8 model; print arena_used_bytes() and trim.
  constexpr int kArenaSize = 96 * 1024;
  alignas(16) uint8_t tensor_arena[kArenaSize];
}

/* ========================= Slaney mel scale (htk=False) ========================= */
static inline float hz_to_mel(float f) {
  const float f_sp = 200.0f / 3.0f;
  const float min_log_hz = 1000.0f;
  const float min_log_mel = min_log_hz / f_sp;          // 15.0
  const float logstep = 0.0687517774209491f;            // ln(6.4)/27
  float mels = f / f_sp;
  if (f >= min_log_hz) mels = min_log_mel + logf(f / min_log_hz) / logstep;
  return mels;
}
static inline float mel_to_hz(float mel) {
  const float f_sp = 200.0f / 3.0f;
  const float min_log_hz = 1000.0f;
  const float min_log_mel = min_log_hz / f_sp;
  const float logstep = 0.0687517774209491f;
  float freq = f_sp * mel;
  if (mel >= min_log_mel) freq = min_log_hz * expf(logstep * (mel - min_log_mel));
  return freq;
}

/* ========================= FFT (radix-2) ========================= */
static void fft_radix2(float* re, float* im) {
  const int n = N_FFT;
  for (int i = 1, j = 0; i < n; i++) {
    int bit = n >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) {
      float tr = re[i]; re[i] = re[j]; re[j] = tr;
      float ti = im[i]; im[i] = im[j]; im[j] = ti;
    }
  }
  for (int len = 2; len <= n; len <<= 1) {
    int half = len >> 1;
    int step = n / len;
    for (int i = 0; i < n; i += len) {
      int k = 0;
      for (int j = 0; j < half; j++) {
        float wr = twCos[k], wi = twSin[k];
        int a = i + j, b = a + half;
        float ur = re[a], ui = im[a];
        float vr = re[b] * wr - im[b] * wi;
        float vi = re[b] * wi + im[b] * wr;
        re[a] = ur + vr; im[a] = ui + vi;
        re[b] = ur - vr; im[b] = ui - vi;
        k += step;
      }
    }
  }
}

/* ========================= Build tables (once) ========================= */
void build_logmel_tables() {
  for (int n = 0; n < N_FFT; n++)
    hannP[n] = 0.5f - 0.5f * cosf(2.0f * (float)M_PI * n / (float)N_FFT);

  for (int k = 0; k < N_FFT / 2; k++) {
    float ang = 2.0f * (float)M_PI * k / (float)N_FFT;
    twCos[k] =  cosf(ang);
    twSin[k] = -sinf(ang);
  }

  // Slaney mel filterbank, area-normalized, stored sparsely (contiguous run
  // of nonzero weights per filter). Mirrors librosa.filters.mel exactly.
  float mel_f[N_MELS + 2];
  float mn = hz_to_mel(MEL_FMIN), mx = hz_to_mel(MEL_FMAX);
  for (int i = 0; i < N_MELS + 2; i++) {
    float mel = mn + (mx - mn) * (float)i / (float)(N_MELS + 1);
    mel_f[i] = mel_to_hz(mel);
  }
  melTotal = 0;
  for (int i = 0; i < N_MELS; i++) {
    float lo_hz = mel_f[i], ce_hz = mel_f[i + 1], hi_hz = mel_f[i + 2];
    float fdiff_lo = ce_hz - lo_hz;
    float fdiff_hi = hi_hz - ce_hz;
    float enorm    = 2.0f / (hi_hz - lo_hz);            // Slaney area norm
    melStart[i] = 0; melLen[i] = 0; melOff[i] = melTotal;
    int started = 0;
    for (int k = 0; k < K; k++) {
      float f = (float)k * SAMPLE_RATE / (float)N_FFT;
      float lower = (f - lo_hz) / fdiff_lo;
      float upper = (hi_hz - f) / fdiff_hi;
      float w = lower < upper ? lower : upper;
      if (w < 0.0f) w = 0.0f;
      w *= enorm;
      if (w > 0.0f) {
        if (!started) { melStart[i] = k; started = 1; }
        if (melTotal < MEL_W_MAX) melWeights[melTotal++] = w;
        melLen[i]++;
      } else if (started) {
        break;                                          // triangle is contiguous
      }
    }
  }
}

/* ========================= mel power of the current frame ========================= */
// frameBuf already holds N_FFT samples in ~[-1,1] (divided by 32768 on load).
// Windows, FFTs, and folds into mel POWER (pre-dB). Writes column `col`.
static void mel_power_from_frameBuf(int col) {
  for (int n = 0; n < N_FFT; n++) { fftRe[n] = frameBuf[n] * hannP[n]; fftIm[n] = 0.0f; }
  fft_radix2(fftRe, fftIm);
  for (int k = 0; k < K; k++) powr[k] = fftRe[k] * fftRe[k] + fftIm[k] * fftIm[k];
  for (int m = 0; m < N_MELS; m++) {
    const float* w = &melWeights[melOff[m]];
    const float* p = &powr[melStart[m]];
    int len = melLen[m];
    float acc = 0.0f;
    for (int j = 0; j < len; j++) acc += w[j] * p[j];
    specWin[m * FRAMES_PER_DECISION + col] = acc;       // store POWER
  }
}

#if USE_CLIP_BUFFER
// MODE B: exact center=True framing from a buffered int16 clip.
// Frame t reads clipBuf[base+j], base = t*HOP - N_FFT/2, out-of-range -> 0.
static void mel_power_from_clip(int t) {
  int base = t * HOP_LENGTH - (N_FFT / 2);
  for (int j = 0; j < N_FFT; j++) {
    int idx = base + j;
    float s = (idx >= 0 && idx < CLIP_LEN) ? clipBuf[idx] * (1.0f / 32768.0f) : 0.0f;
    fftRe[j] = s * hannP[j];
    fftIm[j] = 0.0f;
  }
  fft_radix2(fftRe, fftIm);
  for (int k = 0; k < K; k++) powr[k] = fftRe[k] * fftRe[k] + fftIm[k] * fftIm[k];
  for (int m = 0; m < N_MELS; m++) {
    const float* w = &melWeights[melOff[m]];
    const float* p = &powr[melStart[m]];
    int len = melLen[m];
    float acc = 0.0f;
    for (int j = 0; j < len; j++) acc += w[j] * p[j];
    specWin[m * FRAMES_PER_DECISION + t] = acc;
  }
}
#endif

/* ========================= window -> dB -> mean patch ========================= */
// specWin holds mel POWER for all FRAMES_PER_DECISION columns. Convert with
// global-max ref, cut N_PATCHES patches (hop PATCH_HOP), average into meanPatch.
static void finalize_mean_patch() {
  const int total = N_MELS * FRAMES_PER_DECISION;

  // power_to_db(ref = global max over the window), floor at -TOP_DB.
  float maxmel = 0.0f;
  for (int i = 0; i < total; i++) if (specWin[i] > maxmel) maxmel = specWin[i];
  float ref_db = 10.0f * log10f(maxmel > AMIN ? maxmel : AMIN);
  for (int i = 0; i < total; i++) {
    float v  = specWin[i] > AMIN ? specWin[i] : AMIN;
    float db = 10.0f * log10f(v) - ref_db;              // peaks at 0
    specWin[i] = db < -TOP_DB ? -TOP_DB : db;
  }

  // Average the N_PATCHES patches (hop PATCH_HOP) -> meanPatch (mel-major).
  for (int i = 0; i < PATCH_LEN; i++) meanPatch[i] = 0.0f;
  for (int p = 0; p < N_PATCHES; p++) {
    int start = p * PATCH_HOP;
    for (int m = 0; m < N_MELS; m++) {
      const float* row = &specWin[m * FRAMES_PER_DECISION + start];
      float* dst = &meanPatch[m * PATCH_FRAMES];
      for (int f = 0; f < PATCH_FRAMES; f++) dst[f] += row[f];
    }
  }
  const float inv = 1.0f / (float)N_PATCHES;
  for (int i = 0; i < PATCH_LEN; i++) meanPatch[i] *= inv;
}

/* ========================= CNN2D inference (from test_cnn_2d.ino) ========================= */
// meanPatch is length PATCH_LEN, mel-major (index = mel*PATCH_FRAMES + frame),
// matching the model's NHWC [H=mel][W=frame][C=1] input. Returns P(leak) or -1.
static float run_inference(const float* patch) {
  // The PyTorch CNN2D was trained on per-mel standardized log-mel values.
  // meanPatch[] contains raw dB values, so reproduce the training scaler here
  // before writing/quantizing the TFLite input tensor.
  if (input->type == kTfLiteFloat32) {
    for (int i = 0; i < PATCH_LEN; ++i) {
      const int mel = i / PATCH_FRAMES;
      const float x_std =
          (patch[i] - dataMean[mel]) / dataStd[mel];
      input->data.f[i] = x_std;
    }
  } else if (input->type == kTfLiteInt8) {
    const float scale = input->params.scale;
    const int   zp    = input->params.zero_point;
    for (int i = 0; i < PATCH_LEN; ++i) {
      const int mel = i / PATCH_FRAMES;
      const float x_std =
          (patch[i] - dataMean[mel]) / dataStd[mel];
      int q = (int)lroundf(x_std / scale) + zp;
      if (q < -128) q = -128; else if (q > 127) q = 127;
      input->data.int8[i] = (int8_t)q;
    }
  } else {
    MicroPrintf("Unsupported input tensor type: %d", input->type);
    return -1.0f;
  }

  if (interpreter->Invoke() != kTfLiteOk) { MicroPrintf("Invoke() failed"); return -1.0f; }

  float logits[N_CLASSES];
  if (output->type == kTfLiteFloat32) {
    for (int c = 0; c < N_CLASSES; ++c) logits[c] = output->data.f[c];
  } else if (output->type == kTfLiteInt8) {
    const float scale = output->params.scale;
    const int   zp    = output->params.zero_point;
    for (int c = 0; c < N_CLASSES; ++c) logits[c] = (output->data.int8[c] - zp) * scale;
  } else {
    MicroPrintf("Unsupported output tensor type: %d", output->type);
    return -1.0f;
  }

  const float m  = logits[0] > logits[1] ? logits[0] : logits[1];
  const float e0 = expf(logits[0] - m);
  const float e1 = expf(logits[1] - m);
  return (LEAK_INDEX == 1) ? e1 / (e0 + e1) : e0 / (e0 + e1);
}

/* ========================= decide (inference + EWMA + output) ========================= */
static void decide_from_meanPatch() {
  tInf0 = micros();
  float pLeak = run_inference(meanPatch);
  unsigned long infUs = micros() - tInf0;
  if (pLeak < 0.0f) return;

  if (!ewmaInit) { ewma = pLeak; ewmaInit = true; }
  else           { ewma = EWMA_ALPHA * pLeak + (1.0f - EWMA_ALPHA) * ewma; }

  bool leak = (ewma >= EWMA_THRESHOLD);

  Serial.print("p(leak)="); Serial.print(pLeak, 4);
  Serial.print("  ewma=");  Serial.print(ewma, 4);
  Serial.print("  -> ");    Serial.print(leak ? "LEAK" : "OK");
#if DEBUG_PRINT
  Serial.print("\n inference us="); Serial.print(infUs); Serial.print(")");
#endif
  Serial.println();

  digitalWrite(LEDR, leak ? LOW : HIGH);       // red ON = leak

#if EWMA_RESET_PER_WINDOW
  ewmaInit = false;                            // restart smoothing next window
#endif
}

/* ========================= PDM ISR + ring helpers ========================= */
void onPDMdata() {
  static int16_t tmp[256];
  int bytes = PDM.available();
  if (bytes > (int)sizeof(tmp)) bytes = sizeof(tmp);
  PDM.read(tmp, bytes);
  int n = bytes / 2;
  uint32_t w = ringWrite;
  for (int i = 0; i < n; i++) audioRing[(w + i) & RING_MASK] = tmp[i];
  ringWrite = w + n;
}
static inline uint32_t ring_available() { return ringWrite - ringRead; }

// Pull HOP new samples into the tail of frameBuf (shift down first), scaling
// int16 -> ~[-1,1] by /32768 to match training amplitude (AMIN floor parity).
static void load_hop() {
  memmove(frameBuf, frameBuf + HOP_LENGTH, (N_FFT - HOP_LENGTH) * sizeof(float));
  for (int i = 0; i < HOP_LENGTH; i++)
    frameBuf[N_FFT - HOP_LENGTH + i] =
        (float)audioRing[(ringRead + i) & RING_MASK] * (1.0f / 32768.0f);
  ringRead += HOP_LENGTH;
}

/* ========================= setup ========================= */
void setup() {
  Serial.begin(115200);
  unsigned long t0 = millis();
  while (!Serial && millis() - t0 < 3000) {}

  pinMode(LEDR, OUTPUT); digitalWrite(LEDR, HIGH);
  pinMode(LEDG, OUTPUT); digitalWrite(LEDG, HIGH);
  pinMode(LEDB, OUTPUT); digitalWrite(LEDB, HIGH);

  build_logmel_tables();
  Serial.print("mel weights stored: "); Serial.print(melTotal); Serial.println(" (expect 981)");
  Serial.print("frames/decision: ");    Serial.print(FRAMES_PER_DECISION);
  Serial.print("  patches: ");          Serial.print(N_PATCHES);
  Serial.print(" x ("); Serial.print(N_MELS); Serial.print("x"); Serial.print(PATCH_FRAMES);
  Serial.print(") hop "); Serial.println(PATCH_HOP);

  tflite::InitializeTarget();
  model = tflite::GetModel(g_model);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    MicroPrintf("Model schema %d != %d", model->version(), TFLITE_SCHEMA_VERSION);
    while (true) {}
  }
  // Ops emitted by the CNN2D graph (see test_cnn_2d.ino).
  resolver.AddConv2D();
  resolver.AddMaxPool2D();
  resolver.AddMean();            // global-avg-pool as ReduceMean
  resolver.AddAveragePool2D();   // ...or as AVERAGE_POOL_2D
  resolver.AddFullyConnected();
  resolver.AddReshape();
  resolver.AddRelu();

  static tflite::MicroInterpreter static_interpreter(
      model, resolver, tensor_arena, kArenaSize);
  interpreter = &static_interpreter;
  if (interpreter->AllocateTensors() != kTfLiteOk) {
    MicroPrintf("AllocateTensors() failed -- increase kArenaSize");
    while (true) {}
  }
  input  = interpreter->input(0);
  output = interpreter->output(0);
  MicroPrintf("Input dims: %d %d %d %d",
              input->dims->data[0], input->dims->data[1],
              input->dims->data[2], input->dims->data[3]);
  MicroPrintf("Arena used: %u bytes", (unsigned)interpreter->arena_used_bytes());

  PDM.onReceive(onPDMdata);
  if (!PDM.begin(1, SAMPLE_RATE)) {
    Serial.println("ERROR: PDM init failed");
    while (true) {}
  }

  Serial.println(USE_CLIP_BUFFER ? "Running (MODE B: clip buffer, center=True)."
                                 : "Running (MODE A: streaming).");
  digitalWrite(LEDB, LOW);                      // blue ON = listening
  tFeat0 = micros();
}

/* ========================= loop ========================= */
#if !USE_CLIP_BUFFER
// ---- MODE A: streaming spectrogram window ----
void loop() {
  if (ring_available() < (uint32_t)HOP_LENGTH) return;
  load_hop();

  // Prime: need N_FFT/HOP hops before the first frame is fully valid.
  if (hopsLoaded < (N_FFT / HOP_LENGTH)) { hopsLoaded++; return; }

  unsigned long t0 = micros();
  mel_power_from_frameBuf(specCol);
  totalFrameComputeUs += micros() - t0;

  specCol++;
  
  if (specCol >= FRAMES_PER_DECISION) {
    unsigned long tFinalize0 = micros();
    finalize_mean_patch();
    unsigned long finalizeUs = micros() - tFinalize0;

#if DEBUG_PRINT
    unsigned long featUs = totalFrameComputeUs; //micros() - tFeat0;
    Serial.print(" feature us="); Serial.print(featUs); Serial.println(" ==");
    Serial.print(" finalize us="); Serial.print(finalizeUs); Serial.println(" ==");
#endif
    decide_from_meanPatch();
    specCol = 0;                                // tumbling window
    tFeat0 = micros();

    totalFrameComputeUs = 0;
  }
}

#else
// ---- MODE B: buffer CLIP_LEN samples, then exact center=True extraction ----
void loop() {
  if (ring_available() < (uint32_t)HOP_LENGTH) return;

  // Drain the ring into the clip buffer one hop at a time.
  int room = CLIP_LEN - clipFill;
  int take = room < HOP_LENGTH ? room : HOP_LENGTH;
  for (int i = 0; i < take; i++)
    clipBuf[clipFill + i] = audioRing[(ringRead + i) & RING_MASK];
  clipFill += take;
  ringRead += HOP_LENGTH;

  if (clipFill >= CLIP_LEN) {
    tFeat0 = micros();
    int Tc = FRAMES_PER_DECISION < MAX_FRAMES ? FRAMES_PER_DECISION : MAX_FRAMES;
    for (int t = 0; t < Tc; t++) mel_power_from_clip(t);

    unsigned long tFinalize0 = micros();
    finalize_mean_patch();
    unsigned long finalizeUs = micros() - tFinalize0;
    decide_from_meanPatch();

#if DEBUG_PRINT
    unsigned long featUs = micros() - tFeat0;
    Serial.print("== clip ("); Serial.print(Tc);
    Serial.print(" feature us="); Serial.print(featUs); Serial.println(" ==");
    Serial.print(" finalize us="); Serial.print(finalizeUs); Serial.println(" ==");
#endif
    
    
    clipFill = 0;                               // next clip
    totalFrameComputeUs = 0;
  }
}
#endif
